//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  SOKOIL VIPER Template generated by Michail Vdovin
//

import UIKit

import LightRoute

class ___VARIABLE_productName:identifier___Router: ___VARIABLE_productName:identifier___RouterProtocol {

    private let tempIdentifier = "tempIdentifier"
    weak var transitionHandler: TransitionHandler?
    
    func navigate(with data: String) {
        try? transitionHandler?
            .forCurrentStoryboard(restorationId: tempIdentifier, to: ___VARIABLE_productName:identifier___Input.self)
            .to(preferred: .navigation(style: .push))
            .then { [data] moduleInput in
                moduleInput.configure(data: data)
        }
    }
}
