//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  SOKOIL VIPER Template generated by Michail Vdovin
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: BaseViewController, ___VARIABLE_productName:identifier___Input {

    @IBOutlet weak var mTableView: UITableView!
    let disposeBag = DisposeBag()
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.loadData()
    }
    
    func configure(data: String) {
        presenter?.configure(data: data)
    }
    
    deinit {
        hideProgress()
    }
}

extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewProtocol {
    
    func showData(data: [TempData]) {
        mTableView.dataSource = nil
        let obs = Observable.just(data)
        obs.bind(to: mTableView.rx.items) { tableView, row, element in
            let cell = UITableViewCell.init(style: .default, reuseIdentifier: "cell")
            cell.textLabel?.text = element.name
            return cell
            }.disposed(by: disposeBag)
    }
}
